/**
 * Mock data for the Party-DJ demo.
 *
 * Cover URLs are populated at build time from `data/mock-covers.json`, which is
 * generated by `scripts/fetch-mock-covers.ts` (queries the iTunes Search API).
 * Tracks with no cached cover fall back to a generic placeholder.
 */

import coversJson from "@/data/mock-covers.json";

export type Track = {
  id: string;
  title: string;
  artist: string;
  coverUrl: string;
  bpm: number;
  durationMs: number;
  genre: string;
  /** Mirror der `SnapshotTrack`-Felder; nur in Production-Snapshots gesetzt. */
  source?: 'guest' | 'brain';
  submissionId?: string;
  guestName?: string;
};

export type MoodOption = { emoji: string; label: string; value: string };
export type MoodQuestion = {
  id: string;
  question: string;
  options: MoodOption[];
};

const FALLBACK_COVER =
  "https://via.placeholder.com/600x600.png?text=No+Cover";

const COVERS: Readonly<Record<string, string | null>> = coversJson;

function cover(id: string): string {
  return COVERS[id] ?? FALLBACK_COVER;
}

export const MOCK_PLAYLISTS: string[] = [
  "Warm-Up",
  "Peak Time",
  "Banger",
  "House",
  "Hip-Hop",
  "80s Hits",
  "Latino",
  "Indie",
  "Closer",
];

export const MOCK_TRACKS: Track[] = [
  // House / Electronic
  {
    id: "mock-1",
    title: "Strobe",
    artist: "deadmau5",
    coverUrl: cover("mock-1"),
    bpm: 128,
    durationMs: 637_000, // 10:37
    genre: "House",
  },
  {
    id: "mock-2",
    title: "One More Time",
    artist: "Daft Punk",
    coverUrl: cover("mock-2"),
    bpm: 123,
    durationMs: 320_000, // 5:20
    genre: "House",
  },
  {
    id: "mock-3",
    title: "Summer",
    artist: "Calvin Harris",
    coverUrl: cover("mock-3"),
    bpm: 128,
    durationMs: 222_000, // 3:42
    genre: "House",
  },
  // Hip-Hop
  {
    id: "mock-4",
    title: "Still D.R.E.",
    artist: "Dr. Dre",
    coverUrl: cover("mock-4"),
    bpm: 93,
    durationMs: 270_000, // 4:30
    genre: "Hip-Hop",
  },
  {
    id: "mock-5",
    title: "HUMBLE.",
    artist: "Kendrick Lamar",
    coverUrl: cover("mock-5"),
    bpm: 150,
    durationMs: 177_000, // 2:57
    genre: "Hip-Hop",
  },
  {
    id: "mock-6",
    title: "Bodak Yellow",
    artist: "Cardi B",
    coverUrl: cover("mock-6"),
    bpm: 125,
    durationMs: 223_000, // 3:43
    genre: "Hip-Hop",
  },
  // 80s
  {
    id: "mock-7",
    title: "Take On Me",
    artist: "a-ha",
    coverUrl: cover("mock-7"),
    bpm: 169,
    durationMs: 226_000, // 3:46
    genre: "80s",
  },
  {
    id: "mock-8",
    title: "Billie Jean",
    artist: "Michael Jackson",
    coverUrl: cover("mock-8"),
    bpm: 117,
    durationMs: 294_000, // 4:54
    genre: "80s",
  },
  // Indie
  {
    id: "mock-9",
    title: "Do I Wanna Know?",
    artist: "Arctic Monkeys",
    coverUrl: cover("mock-9"),
    bpm: 85,
    durationMs: 272_000, // 4:32
    genre: "Indie",
  },
  {
    id: "mock-10",
    title: "The Less I Know The Better",
    artist: "Tame Impala",
    coverUrl: cover("mock-10"),
    bpm: 117,
    durationMs: 216_000, // 3:36
    genre: "Indie",
  },
  // Latin
  {
    id: "mock-11",
    title: "Tití Me Preguntó",
    artist: "Bad Bunny",
    coverUrl: cover("mock-11"),
    bpm: 107,
    durationMs: 243_000, // 4:03
    genre: "Latin",
  },
  {
    id: "mock-12",
    title: "Hips Don't Lie",
    artist: "Shakira",
    coverUrl: cover("mock-12"),
    bpm: 100,
    durationMs: 218_000, // 3:38
    genre: "Latin",
  },
  // Rock
  {
    id: "mock-13",
    title: "Don't Stop Me Now",
    artist: "Queen",
    coverUrl: cover("mock-13"),
    bpm: 156,
    durationMs: 209_000, // 3:29
    genre: "Rock",
  },
  // Pop
  {
    id: "mock-14",
    title: "Don't Start Now",
    artist: "Dua Lipa",
    coverUrl: cover("mock-14"),
    bpm: 124,
    durationMs: 183_000, // 3:03
    genre: "House",
  },
  {
    id: "mock-15",
    title: "Blinding Lights",
    artist: "The Weeknd",
    coverUrl: cover("mock-15"),
    bpm: 171,
    durationMs: 200_000, // 3:20
    genre: "80s",
  },
];

export const MOCK_MOOD_QUESTIONS: MoodQuestion[] = [
  {
    id: "vibe",
    question: "Wie ist die Vibe gerade?",
    options: [
      { emoji: "🥱", label: "Müde", value: "tired" },
      { emoji: "👌", label: "Geht", value: "okay" },
      { emoji: "🔥", label: "Heiß", value: "hot" },
      { emoji: "🚀", label: "Voll Eskalation", value: "peak" },
    ],
  },
  {
    id: "tempo",
    question: "Tempo?",
    options: [
      { emoji: "🐢", label: "Langsam", value: "slow" },
      { emoji: "🚶", label: "Mittel", value: "medium" },
      { emoji: "🏃", label: "Schnell", value: "fast" },
      { emoji: "⚡", label: "Volle Pulle", value: "max" },
    ],
  },
  {
    id: "intensity",
    question: "Härter oder weicher?",
    options: [
      { emoji: "☁️", label: "Weicher", value: "softer" },
      { emoji: "➡️", label: "Gleich", value: "same" },
      { emoji: "🔨", label: "Härter", value: "harder" },
    ],
  },
  {
    id: "style",
    question: "Was darfs sein?",
    options: [
      { emoji: "🎵", label: "Klassiker", value: "classics" },
      { emoji: "🎉", label: "Banger", value: "bangers" },
      { emoji: "💃", label: "Tanzbar", value: "danceable" },
      { emoji: "🛋️", label: "Chill", value: "chill" },
    ],
  },
  {
    id: "audience",
    question: "Wer soll's hören?",
    options: [
      { emoji: "👯", label: "Frauen", value: "women" },
      { emoji: "🕺", label: "Männer", value: "men" },
      { emoji: "🤝", label: "Alle", value: "everyone" },
    ],
  },
  {
    id: "phase",
    question: "Wo sind wir?",
    options: [
      { emoji: "🌅", label: "Davor", value: "warmup" },
      { emoji: "🌃", label: "Mitte", value: "mid" },
      { emoji: "🌌", label: "Endphase", value: "lateNight" },
    ],
  },
];
